version: '3.2'
services:
  server-udp:
    container_name: server
    build: Dockerfile/
    ports:
      - 5005:5005/udp
    volumes:
      - type: bind
        source: /mnt/Data/Toradex/Torizon_VSCode/container-networking/server
        target: /server
    networks:
      - xablau
    working_dir: /server
    command: python3 server-udp.py
  client-udp:
    container_name: client
    build: Dockerfile/
    volumes:
      - type: bind
        source: /mnt/Data/Toradex/Torizon_VSCode/container-networking/client
        target: /client
    networks:
      - xablau
    working_dir: /client
    command: python3 client-udp.py


networks:
  xablau:
    external: false
